### ISSUE TITLE
GCC10 Error: Hexadecimal constant at (1) uses nonstandard X instead of Z [see ‘-fno-allow-invalid-boz’]

### ISSUE THREAD

**Issue by dennisklein** [vmc-project/geant3#17]
**Affects**: probably any geant3 version, we have seen it with 2.7, 3.0, and 3.6.
**Compiler**: GCC10
**OS**: macOS and Linux

**Log**:
```
[  0%] Building Fortran object CMakeFiles/geant321.dir/minicern/ublow.F.o
/home/dklein/projects/geant3/minicern/lnxgs/ublow.F:22:20:

   22 |       data iblan1/x'20202000'/
      |                    1
Error: Hexadecimal constant at (1) uses nonstandard X instead of Z [see ‘-fno-allow-invalid-boz’]
/home/dklein/projects/geant3/minicern/lnxgs/ublow.F:23:19:

   23 |       data mask1/x'000000ff'/
      |                   1
Error: Hexadecimal constant at (1) uses nonstandard X instead of Z [see ‘-fno-allow-invalid-boz’]
```

**Quick fix**: Adding `-DCMAKE_Fortran_FLAGS="-fallow-invalid-boz"`, see also FairRootGroup/FairSoft#295.

If the quick fix is acceptable, I can prepare a PR with a few CMake lines that adds the flag to `${CMAKE_Fortran_FLAGS}` if gfortran >= 10.

**Comment by ihrivnac** [comment]
Hi @dennisklein ,
Thank you for reporting the problem; please, make the PR as you suggest. We just need to be sure that the fix will not affect the compilation with older compiler versions.
