### ISSUE TITLE
specified bound depends on the length of the source argument [-Wstringop-overflow=]

### ISSUE THREAD

**Issue by dennisklein** [vmc-project/geant3#21]
**Geant3**: `3.6`
**OS**: `Fedora 32`
**Compiler**: `gcc (GCC) 10.2.1 20200723 (Red Hat 10.2.1-1)`

```
In file included from /usr/include/string.h:495,
                 from /usr/include/root/Rtypes.h:31,
                 from /usr/include/root/TObject.h:17,
                 from /usr/include/root/TNamed.h:25,
                 from /usr/include/root/TDirectory.h:24,
                 from /usr/include/root/TROOT.h:28,
                 from /home/dklein/projects/geant3/TGeant3/TGeant3TGeo.cxx:390:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘virtual Int_t TGeant3TGeo::VolId(const Text_t*) const’ at /home/dklein/projects/geant3/TGeant3/TGeant3TGeo.cxx:742:11:
/usr/include/bits/string_fortified.h:106:34: warning: ‘char* __builtin___strncpy_chk(char*, const char*, long unsigned int, long unsigned int)’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/dklein/projects/geant3/TGeant3/TGeant3TGeo.cxx: In member function ‘virtual Int_t TGeant3TGeo::VolId(const Text_t*) const’:
/home/dklein/projects/geant3/TGeant3/TGeant3TGeo.cxx:739:22: note: length computed here
  739 |    Int_t len = strlen(name) - 1;
      |                ~~~~~~^~~~~~
```

**Comment by ihrivnac** [comment]
Hi @dennisklein ,
Thank you for reporting this. Could you, please, try if the change below fixes the warning?
(I dont't have this gcc version.)

```
--- a/TGeant3/TGeant3TGeo.cxx
+++ b/TGeant3/TGeant3TGeo.cxx
@@ -739,7 +739,7 @@ Int_t TGeant3TGeo::VolId(const Text_t *name) const
    Int_t len = strlen(name) - 1;
    if (name[len] != ' ')
       return fMCGeo->VolId(name);
-   strncpy(sname, name, len);
+   strncpy(sname, name, sizeof(sname));
    sname[len] = 0;
    return fMCGeo->VolId(sname);
 }

```

**Comment by dennisklein** [comment]
> Could you, please, try if the change below fixes the warning?
> (I dont't have this gcc version.)
> 
> ```
> --- a/TGeant3/TGeant3TGeo.cxx
> +++ b/TGeant3/TGeant3TGeo.cxx
> @@ -739,7 +739,7 @@ Int_t TGeant3TGeo::VolId(const Text_t *name) const
>     Int_t len = strlen(name) - 1;
>     if (name[len] != ' ')
>        return fMCGeo->VolId(name);
> -   strncpy(sname, name, len);
> +   strncpy(sname, name, sizeof(sname));
>     sname[len] = 0;
>     return fMCGeo->VolId(sname);
>  }
> ```

Yes, this fixes the warning with gcc 10.2.1.

**Comment by dennisklein** [comment]
```cpp
Int_t TGeant3TGeo::VolId(const Text_t *name) const
{
  //
  // Return the unique numeric identifier for volume name  
  //
  char sname[20];
  Int_t len = strlen(name) - 1;
  if (name[len] != ' ')
    return fMCGeo->VolId(name);
  strncpy(sname, name, sizeof(sname));
  sname[len] = 0;
  return fMCGeo->VolId(sname);
}
```

Even with the warning fixed, looking at this function, I am honestly puzzled.
1. It will still break, if `strlen(name)` is 0.
2. What is it doing?
   * If the last character of `name` is not a space, it will return the numeric id of `name` (no matter what length).
   * If the last character of `name` is a space, it will return the numeric id of maximum the first 20 characters of `name` :confused: ?!

I cannot believe that "last character is a space" can have this special meaning to truncate the name to 20 characters ...

My guess is, the intention was to implement right trimming of spaces (probably even any whitespace), which went wrong somehow. If my guess is right, please consider a fix like the following (which also handles the case when `name` is empty):

```diff
--- a/TGeant3/TGeant3TGeo.cxx
+++ b/TGeant3/TGeant3TGeo.cxx
@@ -735,13 +735,11 @@ Int_t TGeant3TGeo::VolId(const Text_t *name) const
    //
    // Return the unique numeric identifier for volume name
    //
-   char sname[20];
-   Int_t len = strlen(name) - 1;
-   if (name[len] != ' ')
-      return fMCGeo->VolId(name);
-   strncpy(sname, name, len);
-   sname[len] = 0;
-   return fMCGeo->VolId(sname);
+   std::string volname(name);
+   while (!volname.empty() && volname.back() == ' ') {
+      volname.pop_back();
+   }
+   return fMCGeo->VolId(volname.c_str());
 }

```

**Comment by ihrivnac** [comment]
Hi @dennisklein,
Thanks for your investigations; when looking for the fix, I also noticed that the code removes just the last space.  To be sure that we will  not introduce a side effect for this changed I looked into TGeo code, how the spaces are handled here; the removal of spaces (n the context of volumes) happens in TGeoBuilder::Volume(..), where there is used TString::Strip() function:
```
   TString sname = name;
   sname = sname.Strip();
   const char *vname = sname.Data();
```

Though this does the same as your code, I think we should better prefer this one, as in general TGeant3TGeo is using TString instead of std::string. So the final fix would be:

```
Int_t TGeant3TGeo::VolId(const Text_t *name) const
{
   //
   // Return the unique numeric identifier for volume name
   //
   TString sname = name;
   sname = sname.Strip();
   return fMCGeo->VolId(sname.Data());
}

```

**Comment by dennis** [comment]
FYI: Please dont use @dennis unless you wish to notify me

**Comment by ihrivnac** [comment]
> FYI: Please dont use @dennis unless you wish to notify me

Sorry about that; I mismatched your nickname with another Dennis.

**Comment by ihrivnac** [comment]
@dennisklein ,
The fix is now committed:
https://github.com/vmc-project/geant3/commit/c734363384277b503fe537d81731897dff972b32

**Comment by dennisklein** [comment]
@ihrivnac I learned today, that fixed-length space-trailed(!) strings are an actual thing in Fortran. See e.g. http://starlink.eao.hawaii.edu/docs/sun209.htx/sun209se6.html.

After a quick look with @MohammadAlTurany he believes our fix might be ok, but in case you are not super familiar with Fortran (I am certainly not), we may want to double check this change here with the experts again. @MohammadAlTurany commented we need to check, if the supplied `name` argument is already a converted C string or if it is pointing to unconverted Fortran memory.

**Comment by dennisklein** [comment]
Looking again at the original code with the knowledge about Fortran strings and speculating:

```cpp
Int_t TGeant3TGeo::VolId(const Text_t *name) const
{
  char sname[20]; // Maybe it is known that geant3 only uses identifiers of
                  // maximum length of 19 characters (because Fortran strings
                  // are fixed-length and this is the chosen length in geant3)
  Int_t len = strlen(name) - 1; // Still does not handle the case of empty C strings!
                                // Space characters would be counted, but why
                                // count length at all? if Fortran string length is
                                // known - actually applying strlen to a Fortran string is UB!
  if (name[len] != ' ')  // Check for trailing space to determine if it is a Fortran string or not.
                         // What if the Fortran string is exactly 19 characters long? Maybe
                         // the implementer knows that they cannot be longer than 18 characters?
    // It is assumed to be a C string, so nothing to do, just pass on to the other C++ interface.
    return fMCGeo->VolId(name);

  // It is assumed to be a Fortran string, so continue with a conversion?
  strncpy(sname, name, len); // This would copy also the trailing spaces. The compiler
                             // warning can be ignored because len is a maximum of 18 in the Fortran case.
  sname[len] = 0; // Add 0-termination to become a C string
  return fMCGeo->VolId(sname);
}
```

So, even if it was meant to be a conditional Fortran to C string conversion after all it still does not add up for me ;)

**Comment by ihrivnac** [comment]
I believe the fix is safe. This function in TGeant3TGeo deals with TGeo geometry, it overrides the function implementation defined in TGeant3 which deals with geant3 geometry. Also, in geant3,  it is called only in functions which implement TVirtualMC and which are not used by geant3 itself, so I think, that the only danger could be inconsistency between the implementation of  TVirtualMC::Gsvolu() function, where the volumes names are defined and this one, and this potential  inconsistency is fixed with this fix.
I will run a test with AliRoot/O2 in let you know if I see any problems.
