### ISSUE TITLE
ARM64 compilation

### ISSUE THREAD

**Issue by fegray** [vmc-project/geant3#32]
I was referred here by the FairSoft maintainers: to compile on ARM64 linux (a Linux VM on a MacBook with the Apple M1 processor), I had to change the first line of geant3/added/dummies.c slightly:

`#if (defined(__linux) && !defined(__ia64) && !defined(__aarch64__))
`

**Comment by ihrivnac** [comment]
@fegray , thank you. I will check it soon and let you know when the fix is included.

**Comment by ihrivnac** [comment]
Your fix is now included. Can you check?

Also, can you provide me your full name and affiliation so that we can give you credits for this fix in the history file? Thank you.
