### ISSUE TITLE
TGeant3 link doesn't work

### ISSUE THREAD

**Issue by ustajan** [vmc-project/geant3#37]
Broken link in the README -- https://root.cern.ch/vmc

**Comment by ihrivnac** [comment]
Dear @ustajan ,

Thank you for reporting this; the VMC documentation is now available from: : https://vmc-project.github.io/.  I will review the README page and update it soon.

**Comment by ihrivnac** [comment]
The README files is updated: https://github.com/vmc-project/geant3/pull/39
