### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by ustajan** [vmc-project/geant3#38]
Build fails at the linking stage with the following error:

`[100%] Building CXX object CMakeFiles/geant321.dir/geant321_dict.cxx.o
[100%] Linking CXX shared library libgeant321.dylib
ld: library not found for -lROOT::EGPythia6
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libgeant321.dylib] Error 1
make[1]: *** [CMakeFiles/geant321.dir/all] Error 2
make: *** [all] Error 2
`

Additional info:
ROOT Version: 6.26/04
MAC OS X 12.5

Also, here is my cmake command that preceded the build:
`
cmake -DCMAKE_INSTALL_PREFIX=~/git/geant3_install -DVMC_DIR=~/git/vmc_install/lib/VMC-2.0.0/ ~/git/geant3
`

**Comment by ihrivnac** [comment]
Hi @ustajan ,

Geant3 requires ROOT built with the `EGPythia6` component; to get it, please, add the `-Dpythia6_nolink=ON` to your ROOT `cmake` configuration. This will build ROOT::EGPythia6 without linking against Pythia6.

To run a VMC application (examples) with Geant3, you need to provide the `Pythia6` at run time. See the documentation: https://vmc-project.github.io/installation/examples/running-examples/

Best regards,
