### ISSUE TITLE
StopTrack() not respected when issued from PreTrack hook

### ISSUE THREAD

**Issue by sawenzel** [vmc-project/geant3#7]
TGeant3 is not respecting the StopTrack call when issued from the PreTrack hook.

As a user, I would like to kill certain tracks when they are started by the engine. The PreTrack hook is the ideal place for this. While this works correctly for TGeant4, I have strong indications that Geant3 ignores this API ( as long as it is called outside of the normal stepping hook ).

@shahor02

**Comment by amorsch** [comment]
One could try (hoping that ISTOP is correctly initialized elsewhere, if not one could do it in 
PreTrack)

--- a/gtrak/gtrack.F
+++ b/gtrak/gtrack.F
@@ -71,7 +71,8 @@ C.
 #endif
 C.
 C.    ------------------------------------------------------------------
-      ISTOP = 0
+C.      ISTOP = 0
+      IF (ISTOP .NE. 0) GO TO 999
       EPSCUR = EPSMAC
       NSTOUT = 0
       INWOLD = 0

**Comment by ihrivnac** [comment]
This does not work. The results from the tests are affected. The numbers of hits are 0 or very low. It looks like after tracking the first track, the other tracks are not transported as the ISTOP is not reinitialised.

**Comment by amorsch** [comment]
Please try with 
`
--- a/TGeant3/TGeant3gu.cxx
+++ b/TGeant3/TGeant3gu.cxx
@@ -551,6 +551,8 @@ void gutrak()
 //
 //    ------------------------------------------------------------------
 //
+     geant3->Gctrak()->istop = 0;
+     
      vmcApplication->PreTrack();
 
`

**Comment by ihrivnac** [comment]
Thank you, now it works fine. 
There is still a small difference between G3/G4 behaviour.
The output from E01 example with added call to StopTrack() in PreTrack and printing messages in start of PreTrack() and Stepping(): 
G3:
====
Starting new track

Starting new track
...

G4:
====
Starting new track
Starting new step
Track -200 0 0  in EXPH  ArgonGas

Starting new track
Starting new step
Track -200 0 0  in EXPH  ArgonGas
...

**Comment by amorsch** [comment]
I think the G4 behavior is a bit problematic. If the track is stopped in PreTrack 
it should not enter Stepping
(for example the stopping condition could be changed again in Stepping).
For G3 one could add a gustep call before exiting, but not sure whether this is the right thing to do.

**Comment by ihrivnac** [comment]
I agree, I will take a look at G4 VMC if we can improve this.

**Comment by ihrivnac** [comment]
The fix is now committed in geant3 master; Geant4 VMC behavior is fixed in Geant4 VMC master, too.

**Comment by sawenzel** [comment]
Thanks a lot. Could you make a new tag?

**Comment by ihrivnac** [comment]
The new tag, v2-7, is now available.
